// Glosario ampliado del mundo prendario (NOM-179-SCFI-2016, PROFECO y CONDUSEF), en lenguaje claro.
export const GLOSARIO = [
  ["Avalúo", "Lo que un valuador dice que vale tu pieza para revenderla, no lo que te costó. Se hace frente a ti."],
  ["Boleta de empeño", "El contrato que te dan al empeñar. Debe traer avalúo, préstamo, tasa, CAT, plazo, condiciones de refrendo y qué pasa si no pagas."],
  ["CAT (Costo Anual Total)", "El costo total del préstamo en un año, con todo incluido: interés, comisiones, almacenaje y seguro. Es el número para comparar entre casas de empeño."],
  ["Casa de empeño", "Negocio que presta dinero a cambio de dejar una pieza en garantía. Debe estar inscrita en el Registro Público de Casas de Empeño de PROFECO."],
  ["Comercialización (remate)", "La venta de tu pieza cuando venció el plazo y no pagaste ni refrendaste."],
  ["Comisión", "Cobro adicional al interés (por avalúo, almacenaje, reposición de boleta, etc.). Toda comisión debe estar en tu contrato y entrar en el CAT."],
  ["Contrato de adhesión", "Formato de contrato que la casa de empeño registra ante PROFECO; es el mismo para todos sus clientes."],
  ["Demasía (remanente)", "Si tu pieza se vendió en más de lo que debías, la diferencia es tuya. La reclamas con tu boleta e identificación, hasta un año después de la venta."],
  ["Desempeño", "Pagar lo que debes (préstamo más intereses) y recuperar tu pieza."],
  ["Desempeño extemporáneo", "Recuperar tu pieza después del vencimiento, pagando un recargo, mientras todavía no se haya vendido."],
  ["IAP (Institución de Asistencia Privada)", "Organización sin fines de lucro que también presta sobre prendas. Suele cobrar menos que una casa comercial."],
  ["Interés", "El costo mensual de usar el dinero prestado. Se calcula sobre el préstamo; la ley prohíbe cobrar interés sobre interés."],
  ["Kilataje", "La pureza del oro: 10k es 41.7 %, 14k es 58.5 %, 18k es 75 % y 24k es oro prácticamente puro."],
  ["Ley .925", "Plata de joyería fina: 92.5 % de plata pura."],
  ["Periodo de gracia", "Días extra después del vencimiento en los que todavía puedes pagar o refrendar, normalmente con recargo."],
  ["Pignorar", "Dejar un bien en garantía de un préstamo; es otra forma de decir empeñar."],
  ["Plazo", "El tiempo que tienes para pagar o refrendar. Empieza el día que firmas."],
  ["Préstamo (principal)", "El dinero que te dan en la mano. Suele ser entre 40 % y 60 % del avalúo, aunque varía por institución."],
  ["Prenda", "La pieza que dejas en garantía: joyas, relojes, electrónicos u otros bienes."],
  ["PROFECO", "La autoridad que regula a las casas de empeño. Ante ella se presentan las quejas."],
  ["Refrendo", "Pagar solo los intereses del periodo para ganar otro plazo. No baja lo que debes del préstamo."],
  ["Traspaso de boleta", "Cambiar tu empeño a otra casa con mejores condiciones: se liquida la deuda actual y tu pieza pasa a la nueva institución."],
  ["Vencimiento", "La fecha límite para pagar o refrendar. Después empieza el periodo de gracia o la venta de la pieza."],
];
