// Datos públicos de casas de empeño (pizarras y simuladores oficiales), consultados el 1-oct-2026.
// Cada cifra lleva su fuente. Reglas para leerlas:
//   - tasaMensual: costo mensual TOTAL (interés + almacenaje) que se usa para calcular. Si la casa
//     publica un rango, se usa el tope (cálculo conservador) y tasaTexto muestra el rango.
//   - prestamoPct: fracción del VALOR DE REFERENCIA DEL METAL que presta. Solo Dondé lo publica por
//     gramo (verificable); en las demás es el porcentaje que publican sobre SU avalúo, suponiendo
//     avalúo ≈ valor del metal → prestamoEstimado: true y el chat lo dice como aproximado.
//   - Sin dato publicado = no se calcula (nunca se inventa).
//   - pagaTarifa: la casa le paga a CAP & Co. cuando alguien se cambia con ella; se dice siempre.
// Plata: ninguna casa publica préstamo por gramo; no se calcula préstamo de plata.

export const FECHA_CASAS = "consultados el 1 de octubre de 2026 (cada casa con la fecha de su pizarra)";
export const FUENTE_CASAS = "pizarras de tasas y simuladores oficiales de cada casa";

export const CASAS = [
  {
    id: "fundacion_donde",
    corto: "Dondé",
    fechaDatos: "pizarra jun-2026; simulador 1-oct-2026",
    nombre: "Fundación Dondé",
    alias: ["donde", "dondé", "rafael donde", "rafael dondé"],
    tipo: "IAP",
    tasaMensual: { general: 12.27 },
    tasaTexto: "12.27 %",
    ivaSobreIntereses: false,
    catTexto: "166 % sin IVA (pagos fijos)",
    prestamoPct: { oro: 0.92 },
    prestamoEstimado: true,
    prestamoTexto: "≈92 % del valor del oro (plan mensual; su avalúo sigue el precio del oro)",
    fuente: "Simulador y pizarra de dondeempenos.com.mx, 1-oct-2026",
  },
  {
    id: "nacional_monte_de_piedad",
    corto: "Monte de Piedad",
    fechaDatos: "pizarra ago-2025",
    nombre: "Nacional Monte de Piedad",
    alias: ["monte de piedad", "nacional monte"],
    tipo: "IAP",
    tasaMensual: { general: 6.14 },
    tasaTexto: "3.7–6.1 %",
    ivaSobreIntereses: false,
    catTexto: "54.7 % a 104.5 % sin IVA",
    prestamoPct: { oro: 0.89 },
    prestamoEstimado: true,
    prestamoTexto: "89 % promedio de su avalúo (70 % a 100 %)",
    nota: "Cerrada por huelga desde 2025; vuelve a abrir el 7 de octubre de 2026, con cita. Su pizarra es de 2025.",
    cerradaHasta: "2026-10-07",
    fuente: "Pizarra tasas-y-costos.pdf de montepiedad.com.mx (V65, ago-2025)",
  },
  {
    id: "montepio_luz_savinon",
    corto: "Montepío L. Saviñón",
    fechaDatos: "pizarra oct-2026",
    nombre: "Montepío Luz Saviñón",
    alias: ["montepio", "montepío", "luz savinon", "luz saviñón"],
    tipo: "IAP",
    tasaMensual: { general: 6.7 },
    tasaTexto: "3.9–6.7 %",
    ivaSobreIntereses: false,
    catTexto: "52.3 % a 117.8 % sin IVA",
    prestamoPct: {},
    prestamoTexto: "hasta 170 % de su avalúo interno (no publica cuánto por gramo)",
    // Le paga a CAP & Co. una tarifa por cada persona que se cambia con ella: para la persona es
    // gratis y el chat lo dice siempre que aparece (LFPC art. 32).
    pagaTarifa: true,
    fuente: "montepio.org.mx/tasas-y-costos (V9, vigente desde 1-oct-2026)",
  },
  {
    id: "first_cash",
    corto: "First Cash",
    fechaDatos: "pizarra ene-2025, vigente a 2027",
    nombre: "First Cash",
    alias: ["firstcash", "first cash", "cash express"],
    tipo: "comercial",
    tasaMensual: { general: 15.99 },
    tasaTexto: "15.99 %",
    ivaSobreIntereses: true,
    catTexto: "191.9 % sin IVA",
    prestamoPct: { oro: 0.6 },
    prestamoEstimado: true,
    prestamoTexto: "60 % promedio de su avalúo",
    fuente: "Pizarra costosycomisiones.pdf de firstcash.mx (vigente a 2027)",
  },
  {
    id: "presta_prenda",
    corto: "Presta Prenda",
    fechaDatos: "jul-2026",
    nombre: "Presta Prenda",
    alias: ["presta prenda", "prestaprenda", "banco azteca"],
    tipo: "comercial",
    tasaMensual: { general: 9.48 },
    tasaTexto: "2.9–9.5 %",
    ivaSobreIntereses: true,
    catTexto: "91 % sin IVA (PP Tradicional)",
    prestamoPct: {},
    prestamoTexto: "de 10 % a más de 100 % de su avalúo",
    fuente: "prestaprenda.com, PP Tradicional (calculado al 31-jul-2026)",
  },
  {
    id: "presto_cash",
    corto: "Presto Cash",
    fechaDatos: "pizarra may-2022",
    nombre: "Presto Cash",
    alias: ["presto cash", "prestocash"],
    tipo: "comercial",
    tasaMensual: { general: 20 },
    tasaTexto: "20 %",
    ivaSobreIntereses: true,
    catTexto: "240 %",
    prestamoPct: { oro: 0.7 },
    prestamoEstimado: true,
    prestamoTexto: "50 % a 90 % del valor del metal (se usa 70 %)",
    nota: "Su pizarra publicada es de 2022.",
    fuente: "Pizarra de prestocash.mx (imagen de may-2022)",
  },
  {
    id: "el_cerrito",
    corto: "El Cerrito",
    fechaDatos: "sitio oficial, sin fecha",
    nombre: "El Cerrito",
    alias: ["el cerrito", "cerrito"],
    tipo: "comercial",
    tasaMensual: {},
    tasaTexto: "cobra por día; no publica tasa mensual",
    ivaSobreIntereses: true,
    catTexto: "144 % con IVA",
    prestamoPct: {},
    prestamoTexto: "hasta 80 % de su avalúo",
    fuente: "cerrito.com.mx/casa-de-empeno",
  },
];
